title: Bot on Cars
author: Wang ZiLiang
email: wang.ziliang@dhs.sg
description: > # this means to ignore newlines until "baseurl:"
  This bot is created with knowledge about cars.

# social links
twitter_username: your-twitter-handle
github_username:  Pyroshark 42

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
